# Generated by Django 6.0.6 on 2026-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AddField(
            model_name='chat',
            name='archived_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='archived_by_hairdresser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_by_hairdresser',
            field=models.BooleanField(default=False),
        ),
    ]
