# Generated by Django 6.0.6 on 2026-06-22 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='hairdressers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'hairdresser'}, related_name='working_at_salons', to=settings.AUTH_USER_MODEL),
        ),
    ]
