# Generated by Django 6.0.6 on 2026-06-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_salon_hairdressers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstylepublication',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hairstyle_publications', to='salons.salon'),
        ),
    ]
