# Generated by Django 6.0.6 on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salon_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair', 'Coiffure'), ('nails', 'Ongles'), ('piercing', 'Piercing'), ('makeup', 'Makeup'), ('skincare', 'Soins')], default='hair', max_length=20),
        ),
    ]
