# Generated by Django 6.0.3 on 2026-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstylepublication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
