# Generated by Django 6.0.3 on 2026-06-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_chat_message'),
        ('salons', '0007_hairstylepublication_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment'),
        ),
    ]
