# Generated by Django 6.0.3 on 2026-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_review_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='subscription_active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
