# Generated by Django 6.0.6 on 2026-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_hairstylepublication_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstylepublication',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='hairstyles/'),
        ),
        migrations.AlterField(
            model_name='hairstylepublication',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='salonpublication',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='salonpublication',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
