# Generated by Django 6.0.6 on 2026-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0013_alter_hairstylepublication_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstylepublication',
            name='category',
            field=models.CharField(choices=[('hair', 'Hairstyle'), ('nails', 'Nails'), ('piercing', 'Piercing'), ('makeup', 'Makeup'), ('skincare', 'Skincare')], default='hair', max_length=20),
        ),
        migrations.AddField(
            model_name='salonpublication',
            name='category',
            field=models.CharField(choices=[('hair', 'Hairstyle'), ('nails', 'Nails'), ('piercing', 'Piercing'), ('makeup', 'Makeup'), ('skincare', 'Skincare')], default='hair', max_length=20),
        ),
    ]
