# Generated by Django 6.0.6 on 2026-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0014_hairstylepublication_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='operator_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='SUCCESSFUL', max_length=20),
        ),
    ]
