# Generated by Django 6.0.6 on 2026-10-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0015_subscriptiontransaction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='salons/'),
        ),
    ]
